# Generated by Django 3.2.9 on 2021-11-12 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_auto_20211112_2119"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="original_bag",
            new_name="original_cart",
        ),
    ]
