# Generated by Django 3.2.9 on 2021-11-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211111_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_available',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
